# Generated by Django 3.2.4 on 2021-06-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='category',
        ),
        migrations.AddField(
            model_name='pins',
            name='category',
            field=models.ManyToManyField(to='pins.Category'),
        ),
    ]
