# Generated by Django 3.2.4 on 2021-07-01 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0003_savepin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, upload_to='all_photos')),
                ('image2', models.ImageField(blank=True, upload_to='all_photos')),
                ('image3', models.ImageField(blank=True, upload_to='all_photos')),
                ('image4', models.ImageField(blank=True, upload_to='all_photos')),
                ('category', models.ManyToManyField(to='pins.Category')),
                ('pins', models.ManyToManyField(related_name='pins', to='pins.Pins')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
