# Generated by Django 3.2.4 on 2021-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pins.Pins'),
        ),
    ]
